runtime: java17
instance_class: F2

entrypoint: java -jar target/Holos-0.0.1-SNAPSHOT.jar --server.port=8080 --spring.datasource.username=root --spring.profiles.active=docker --server.database=holos-db-ppl --spring.datasource.password=rootpassword --spring.datasource.url=jdbc:mysql://34.57.14.19:3306/holos-db-ppl

handlers:
  - url: /.*
    script: this field is required, but ignored
    secure: always
    redirect_http_response_code: 301