name: Auto Fix and Lint Workflow

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

  #comprobar error

  

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run auto-fix with Black and Isort
        run: |
          black . || echo "Black fixed the code"
          isort . || echo "Isort fixed the code"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "Auto-fix lint errors [bot]" || echo "No changes to commit"
          
          # Push the changes to the same branch from which the workflow was triggered
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
