name: Auto Fix and Lint Workflow

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort

      - name: Run auto-fix with Black and Isort
        run: |
          black . --check || black .
          isort . --check-only || isort .

      - name: Show Git Status (Debugging)
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          
          # Verifica si hay cambios en staging antes de hacer commit
          if ! git diff --cached --exit-code; then
            git commit -m "Auto-fix lint errors [bot]"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
