name: Commits Syntax Checker and Lint Commits

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize]
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          config: "@commitlint/config-conventional"

 
      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1.0.3